# NumPy
Numpy is a python package for scientific computing making use of *ndarray* as object.  


In [2]:
#installing numpy
#pip install numpy

#importing numpy
import numpy as np

## What is an Array?
An array is a table of elements(usually numbers) of the same type indexed by a tuple of non negative integers. 
Dimensions in NumPy are called *axis*.
- *dtype* refers to the type of an array
- *rank* refers to the number of dimensions in an array
- *shape* refers to the size of an array along each dimension

In [3]:
# create an array
a = np.array([1,2,3,4,5])

In [7]:
# access elements in an array
b = np.array([[1,2,3,5],[2,3,4,5],[6,7,5,3]])

In [9]:
# print items in an array
print(a[4])

5


## Attributes of Array

### Create Arrays of zeroes

In [10]:
np.zeros(2)

array([0., 0.])

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.zeros((3,4,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

### Create Arrays of ones


In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.ones((5,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### Create array with random elements

In [21]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.empty((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### Create a sequence of arrays

In [26]:
#using the arange function
np.arange(2,10,2)

array([2, 4, 6, 8])

In [36]:
# using linspace
np.linspace(0,10, num=20, dtype = np.int64)

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9, 10], dtype=int64)

### Sorting