# NumPy
Numpy is a python package for scientific computing making use of *ndarray* as object.  


In [2]:
#installing numpy
#pip install numpy

#importing numpy
import numpy as np

## What is an Array?
An array is a table of elements(usually numbers) of the same type indexed by a tuple of non negative integers. 
Dimensions in NumPy are called *axis*.
- *dtype* refers to the type of an array
- *rank* refers to the number of dimensions in an array
- *shape* refers to the size of an array along each dimension

In [3]:
# create an array
a = np.array([1,2,3,4,5])

In [7]:
# access elements in an array
b = np.array([[1,2,3,5],[2,3,4,5],[6,7,5,3]])

In [9]:
# print items in an array
print(a[4])

5


## Attributes of Arrays

### Create Arrays of zeroes

In [10]:
np.zeros(2)

array([0., 0.])

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.zeros((3,4,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

### Create Arrays of ones


In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.ones((5,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### Create array with random elements

In [21]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.empty((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### Create a sequence of arrays

In [26]:
#using the arange function
np.arange(2,10,2)

array([2, 4, 6, 8])

In [36]:
# using linspace
np.linspace(0,10, num=20, dtype = np.int64)

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9, 10], dtype=int64)

### Adding, Removing and Sorting elements

In [51]:
#sorting arrays
a  = np.array([3,4,2,5,6])
np.sort(a)

array([2, 3, 4, 5, 6])

In [55]:
b = np.sort(a)
c = np.array([4,3,2,1,7])
b, c

(array([2, 3, 4, 5, 6]), array([4, 3, 2, 1, 7]))

In [56]:
# concatenate
np.concatenate((b,c))

array([2, 3, 4, 5, 6, 4, 3, 2, 1, 7])

In [64]:
# concatenate by axis
x = np.array([[1,3],[2,4]])
y = np.array([[3,5]])
np.concatenate((x,y))

array([[1, 3],
       [2, 4],
       [3, 5]])

### Shape and Size of an array


In [70]:
my_array = np.array([[[2,3,4],[4,6,7]],
                    [[1,2,3],[3,4,5]],
                    [[3,5,6],[6,7,8]]])
my_array

array([[[2, 3, 4],
        [4, 6, 7]],

       [[1, 2, 3],
        [3, 4, 5]],

       [[3, 5, 6],
        [6, 7, 8]]])

In [71]:
# array dimension
my_array.ndim

3

In [72]:
# number of elements in an array
my_array.size

18

In [73]:
# shape of an array
my_array.shape

(3, 2, 3)

In [80]:
# reshape array
our_array = np.arange(1,21,2)
our_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [84]:
our_array.reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

### Dimension conversion

In [89]:
q = np.array([4,5,6,7,3,2])
q.shape

(6,)

In [90]:
#convert 1D to 2D
q1 = q[np.newaxis,:]
q1.shape

(1, 6)

### Indexing and Slicing

In [91]:
data = np.array([1,4,5,6,7])
data

array([1, 4, 5, 6, 7])

In [93]:
#index third element
data[2]

5

In [94]:
#index first two elements
data[0:2]

array([1, 4])

In [95]:
#index all elemens except the first element
data[1:]

array([4, 5, 6, 7])

In [97]:
#index the  last two elements
data[-2:]

array([6, 7])

In [99]:
g = np.array([[[2,3,4],[4,6,7]],
                    [[1,2,3],[3,4,5]],
                    [[3,5,6],[6,7,8]]])
g

array([[[2, 3, 4],
        [4, 6, 7]],

       [[1, 2, 3],
        [3, 4, 5]],

       [[3, 5, 6],
        [6, 7, 8]]])

In [101]:
# print elements in array less than 5
print(g[g < 6])

[2 3 4 4 1 2 3 3 4 5 3 5]


In [102]:
# print elements in array greater than or equal to 6
print(g[g >= 6])

[6 7 6 6 7 8]


In [104]:
#print elements in array that are divisible by 2
print(g[g%2 == 0])

[2 4 4 6 2 4 6 6 8]


In [108]:
# print elements greater than 2 but less than 10
print(g[(g>2) & (g<11)])

[3 4 4 6 7 3 3 4 5 3 5 6 6 7 8]


In [168]:
# getting unique count of a matrix
c = np.array([1,2,3,3,4,5,6,6,6,9])
np.unique(c)

array([1, 2, 3, 4, 5, 6, 9])

In [169]:
#getting indexes of unique values in an array
np.unique(c, return_index = True)

(array([1, 2, 3, 4, 5, 6, 9]), array([0, 1, 2, 4, 5, 6, 9], dtype=int64))

In [170]:
#get the count or frequency of unique values
np.unique(c, return_counts = True)

(array([1, 2, 3, 4, 5, 6, 9]), array([1, 1, 2, 1, 1, 3, 1], dtype=int64))

In [177]:
# for 2d arrays
my_2d = np.array([[1,2,3],[5,6,6],[1,2,3]])
unique = np.unique(my_2d)
index = np.unique(my_2d, return_index = True)
count = np.unique(my_2d, return_counts=True)
my_2d, unique, index, count

(array([[1, 2, 3],
        [5, 6, 6],
        [1, 2, 3]]),
 array([1, 2, 3, 5, 6]),
 (array([1, 2, 3, 5, 6]), array([0, 1, 2, 3, 4], dtype=int64)),
 (array([1, 2, 3, 5, 6]), array([2, 2, 2, 1, 2], dtype=int64)))

In [178]:
#for unique rows
unique = np.unique(my_2d, axis = 0)
index = np.unique(my_2d, return_index = True, axis=0)
count = np.unique(my_2d, return_counts=True, axis=0)
unique, index, count

(array([[1, 2, 3],
        [5, 6, 6]]),
 (array([[1, 2, 3],
         [5, 6, 6]]),
  array([0, 1], dtype=int64)),
 (array([[1, 2, 3],
         [5, 6, 6]]),
  array([2, 1], dtype=int64)))

In [179]:
#for unique columns
unique = np.unique(my_2d, axis = 1)
index = np.unique(my_2d, return_index = True, axis=1)
count = np.unique(my_2d, return_counts=True, axis=1)
unique, index, count

(array([[1, 2, 3],
        [5, 6, 6],
        [1, 2, 3]]),
 (array([[1, 2, 3],
         [5, 6, 6],
         [1, 2, 3]]),
  array([0, 1, 2], dtype=int64)),
 (array([[1, 2, 3],
         [5, 6, 6],
         [1, 2, 3]]),
  array([1, 1, 1], dtype=int64)))

### Array reversal

In [198]:
# reversing 1D array
array = np.array([1,2,3,4,5])
np.flip(array)

array([5, 4, 3, 2, 1])

In [200]:
# reversing 2D array
array_2d = np.array([[1,2,3],[4,5,6]])
np.flip(array_2d)

array([[6, 5, 4],
       [3, 2, 1]])

In [201]:
#reversing 2D arrays by rows
np.flip(array_2d, axis = 0)

array([[4, 5, 6],
       [1, 2, 3]])

In [202]:
#reversing 2D arrays by columns
np.flip(array_2d, axis = 1)

array([[3, 2, 1],
       [6, 5, 4]])

## Array Operations

In [110]:
# create two arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
a,b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [111]:
#addition operation
a + b

array([ 7,  9, 11, 13, 15])

In [112]:
# multiplication operation
a * b

array([ 6, 14, 24, 36, 50])

In [113]:
# division operation
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [114]:
a ** b

array([      1,     128,    6561,  262144, 9765625])

In [124]:
#broadcasting
c = 8
a * c

array([ 8, 16, 24, 32, 40])

In [129]:
#minimum and maximum number in an array
np.min(a), np.max(a)

(1, 5)

In [131]:
# sum of number in an array
np.sum(a), np.sum(b)

(15, 40)

## Matrices

In [134]:
# creating a matrice
my_matrix = np.array([[1,2],[4,5],[5,6]])
my_matrix

array([[1, 2],
       [4, 5],
       [5, 6]])

In [135]:
# indexing first row and second column
my_matrix[0, 1]

2

In [138]:
# indexing first to last row
my_matrix[1:3]

array([[4, 5],
       [5, 6]])

In [140]:
#indexing first two rows and no columns
my_matrix[0:2, 0]

array([1, 4])

In [144]:
# matrices can also be aggregrated
my_matrix.min(), my_matrix.max(), np.sum(my_matrix)

(1, 6, 23)

In [149]:
#aggregrate by axis
my_matrix.min(axis = 0), my_matrix.max(axis = 0), my_matrix.min(axis = 1), my_matrix.max(axis = 1)

(array([1, 2]), array([5, 6]), array([1, 4, 5]), array([2, 5, 6]))

In [151]:
# summing by axis
my_matrix.sum(axis = 0), my_matrix.sum(axis = 1)

(array([10, 13]), array([ 3,  9, 11]))

In [158]:
# matrix multiplication
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2],[3,4],[5,6]])

A @ B #or
A.dot(B)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

## Generating Random Numbers

In [206]:
# generatae random integers between 0 and 4
rng = np.random.default_rng() 
rng.integers(5, size= (2,4))

array([[4, 1, 2, 3],
       [1, 1, 4, 0]], dtype=int64)

### Transposing a matrix


In [196]:
#transposing
matrix = np.array([[1,2,3],[4,5,6]])
matrix.transpose()
#or 
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [191]:
#reshaping
matrix.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])